[package]
name = "todo-lib"
version = "1.0.0"
edition = "2021"

description = "A todo management library for Rust"

license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datetime = "0.5.2"
